# Generated by Django 6.0.2 on 2026-03-19 15:23

import colorfield.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import re
import tesys_tagboard.enums
import tesys_tagboard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d\\:-_]+$'), message='Enter a valid tag name.')])),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('rating_level', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['category', '-post_count'],
            },
        ),
        migrations.CreateModel(
            name='DefaultPostTag',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tesys_tagboard.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=1000)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('rating_level', models.PositiveSmallIntegerField(choices=[(0, 'SAFE'), (1, 'UNRATED'), (50, 'QUESTIONABLE'), (100, 'EXPLICIT')], default=tesys_tagboard.enums.RatingLevel['UNRATED'])),
                ('src_url', models.URLField(blank=True, default='', max_length=255)),
                ('locked_comments', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('AVIF', 'AVIF image'), ('BMP', 'Windows Bitmap Graphics'), ('GIF', 'GIF'), ('JPEG', 'JPEG image'), ('PNG', 'PNG'), ('WEBP', 'WEBP image'), ('TIFF', 'TIFF image'), ('MP3', 'MP3 audio'), ('WAV', 'WAV audio'), ('WAV2', 'WAV audio'), ('WAV3', 'WAV audio'), ('MP4', 'MP4 video'), ('MPEG', 'MPEG video'), ('WEBM', 'WEBM video')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesys_tagboard.post')),
                ('tags', models.ManyToManyField(blank=True, to='tesys_tagboard.tag')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['post_date'],
                'permissions': [('lock_comments', 'Can lock and unlock the comments of a post')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_comment='The body text of the comment', max_length=500)),
                ('post_date', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the comment was posted')),
                ('edit_date', models.DateTimeField(auto_now=True, db_comment='Date and time when the comment was last edited')),
                ('user', models.ForeignKey(db_comment='The foreign key to the User who posted the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(db_comment='The foreign key to the Post this comment comments on', on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='PostTagHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_time', models.DateTimeField(auto_now_add=True, db_comment="Timestamp of Post's tags modification (including initial)")),
                ('tags', models.CharField(db_comment='Comma-delimited string of tag IDs at the current time', default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Post tag histories',
            },
        ),
        migrations.CreateModel(
            name='SourceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_time', models.DateTimeField(auto_now_add=True, db_comment="Timestamp of Media's source URL modification (including initial)")),
                ('src_url', models.CharField(db_comment='Comma-delimited string of source URLs at the current time', default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Source histories',
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bg', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('fg', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesys_tagboard.tagcategory')),
            ],
            options={
                'verbose_name_plural': 'tag categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.tagcategory'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_name', models.TextField(default='')),
                ('file', models.FileField(unique=True, upload_to=tesys_tagboard.models.media_upload_path)),
                ('md5', models.CharField(validators=[django.core.validators.RegexValidator('^[0-9A-Z]{32}$')])),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tesys_tagboard.tag')),
                ('bio', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_name', models.TextField(default='')),
                ('file', models.ImageField(height_field='height', unique=True, upload_to=tesys_tagboard.models.media_upload_path, width_field='width')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(height_field='thumbnail_height', null=True, upload_to=tesys_tagboard.models.media_thumbnail_upload_path, width_field='thumbnail_width')),
                ('thumbnail_width', models.PositiveIntegerField(default=0)),
                ('thumbnail_height', models.PositiveIntegerField(default=0)),
                ('md5', models.CharField(validators=[django.core.validators.RegexValidator('^[0-9A-Z]{32}$')])),
                ('phash', models.CharField(validators=[django.core.validators.RegexValidator('^[0-9a-z]{16}$')])),
                ('dhash', models.CharField(validators=[django.core.validators.RegexValidator('^[0-9a-z]{16}$')])),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='image_md5_idx'), django.contrib.postgres.indexes.HashIndex(models.F('phash'), name='image_phash_idx'), django.contrib.postgres.indexes.HashIndex(models.F('dhash'), name='image_dhash_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_favorite')],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d_\\- ]+\\Z'), message='Enter a valid collection name.')])),
                ('desc', models.TextField(max_length=1024)),
                ('public', models.BooleanField(blank=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(to='tesys_tagboard.post')),
            ],
            options={
                'permissions': [('add_post_to_collection', 'Can add posts to a collection'), ('remove_post_from_collection', 'Can remove posts from a collection')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_collection_name_user')],
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_name', models.TextField(default='')),
                ('file', models.FileField(unique=True, upload_to=tesys_tagboard.models.media_upload_path)),
                ('md5', models.CharField(validators=[django.core.validators.RegexValidator('^[0-9A-Z]{32}$')])),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='audio_md5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d\\:-_]+$'), message='Enter a valid tag name.')])),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.tag')),
            ],
            options={
                'verbose_name_plural': 'tag aliases',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'tag'), name='unique_tagalias_name_tag')],
            },
        ),
        migrations.AddIndex(
            model_name='tagcategory',
            index=models.Index(fields=['name'], name='tag_category_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='tagcategory',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name_parent', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_tag_name_cat'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='video_md5_idx'),
        ),
    ]
