# Generated by Django 6.0.2 on 2026-03-19 13:19

import colorfield.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import re
import tesys_tagboard.enums
import tesys_tagboard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('BA', 'basic'), ('AR', 'artist'), ('CO', 'copyright')], default='BA', max_length=2)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('rating_level', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['category', '-post_count'],
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_name', models.TextField(default='')),
                ('file', models.FileField(unique=True, upload_to=tesys_tagboard.models.media_upload_path)),
                ('md5', models.CharField(validators=[django.core.validators.RegexValidator('^[0-9A-Z]{32}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(max_length=1024)),
                ('public', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_comment='The body text of the comment', max_length=500)),
                ('post_date', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the comment was posted')),
                ('edit_date', models.DateTimeField(auto_now=True, db_comment='Date and time when the comment was last edited')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_name', models.TextField(default='')),
                ('file', models.ImageField(height_field='height', unique=True, upload_to=tesys_tagboard.models.media_upload_path, width_field='width')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(height_field='height', null=True, upload_to=tesys_tagboard.models.media_thumbnail_upload_path, width_field='width')),
                ('thumbnail_width', models.PositiveIntegerField(default=0)),
                ('thumbnail_height', models.PositiveIntegerField(default=0)),
                ('md5', models.CharField(validators=[django.core.validators.RegexValidator('^[0-9A-Z]{32}$')])),
                ('phash', models.CharField(validators=[django.core.validators.RegexValidator('^[0-9a-z]{16}$')])),
                ('dhash', models.CharField(validators=[django.core.validators.RegexValidator('^[0-9a-z]{16}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=1000)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('rating_level', models.PositiveSmallIntegerField(choices=[(0, 'SAFE'), (1, 'UNRATED'), (50, 'QUESTIONABLE'), (100, 'EXPLICIT')], default=tesys_tagboard.enums.RatingLevel['UNRATED'])),
                ('src_url', models.URLField(blank=True, default='', max_length=255)),
                ('locked_comments', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('AVIF', 'AVIF image'), ('BMP', 'Windows Bitmap Graphics'), ('GIF', 'GIF'), ('JPEG', 'JPEG image'), ('PNG', 'PNG'), ('WEBP', 'WEBP image'), ('MP3', 'MP3 audio'), ('WAV', 'WAV audio'), ('MP4', 'MP4 video'), ('MPEG', 'MPEG video'), ('WEBM', 'WEBM video')], max_length=20)),
            ],
            options={
                'ordering': ['post_date'],
                'permissions': [('lock_comments', 'Can lock and unlock the comments of a post')],
            },
        ),
        migrations.CreateModel(
            name='PostTagHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_time', models.DateTimeField(auto_now_add=True, db_comment="Timestamp of Post's tags modification (including initial)")),
                ('tags', models.CharField(db_comment='Comma-delimited string of tag IDs at the current time', default='')),
            ],
        ),
        migrations.CreateModel(
            name='SourceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_time', models.DateTimeField(auto_now_add=True, db_comment="Timestamp of Media's source URL modification (including initial)")),
                ('src_url', models.CharField(db_comment='Comma-delimited string of source URLs at the current time', default='')),
            ],
        ),
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'tag aliases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_name', models.TextField(default='')),
                ('file', models.FileField(unique=True, upload_to=tesys_tagboard.models.media_upload_path)),
                ('md5', models.CharField(validators=[django.core.validators.RegexValidator('^[0-9A-Z]{32}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tesys_tagboard.tag')),
                ('bio', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_tag_name_cat'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_comment='The foreign key to the User who posted the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tesys_tagboard.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(db_comment='The foreign key to the Post this comment comments on', on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post'),
        ),
        migrations.AddField(
            model_name='collection',
            name='posts',
            field=models.ManyToManyField(to='tesys_tagboard.post'),
        ),
        migrations.AddField(
            model_name='audio',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post'),
        ),
        migrations.AddField(
            model_name='posttaghistory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post'),
        ),
        migrations.AddField(
            model_name='posttaghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourcehistory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post'),
        ),
        migrations.AddField(
            model_name='sourcehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagalias',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.tag'),
        ),
        migrations.AddField(
            model_name='video',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_favorite'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_collection_name_user'),
        ),
        migrations.AddConstraint(
            model_name='tagalias',
            constraint=models.UniqueConstraint(fields=('name', 'tag'), name='unique_tagalias_name_tag'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(height_field='thumbnail_height', null=True, upload_to=tesys_tagboard.models.media_thumbnail_upload_path, width_field='thumbnail_width'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesys_tagboard.post'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_date',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AVIF', 'AVIF image'), ('BMP', 'Windows Bitmap Graphics'), ('GIF', 'GIF'), ('JPEG', 'JPEG image'), ('PNG', 'PNG'), ('WEBP', 'WEBP image'), ('TIFF', 'TIFF image'), ('MP3', 'MP3 audio'), ('WAV', 'WAV audio'), ('WAV2', 'WAV audio'), ('WAV3', 'WAV audio'), ('MP4', 'MP4 video'), ('MPEG', 'MPEG video'), ('WEBM', 'WEBM video')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='audio_md5_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='image_md5_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.HashIndex(models.F('phash'), name='image_phash_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.HashIndex(models.F('dhash'), name='image_dhash_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(models.F('category'), name='tag_category_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='video_md5_idx'),
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': [('add_post_to_collection', 'Can add posts to a collection'), ('remove_post_from_collection', 'Can remove posts from a collection')]},
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bg', models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$')])),
                ('fg', models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$')])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='tag_category_idx',
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesys_tagboard.tagcategory'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.tagcategory'),
        ),
        migrations.AddIndex(
            model_name='tagcategory',
            index=models.Index(models.F('name'), name='tag_category_name_idx'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='bg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='fg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.CreateModel(
            name='DefaultPostTag',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tesys_tagboard.tag')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d\\:-_]+$'), message='Enter a valid tag name.')]),
        ),
        migrations.AlterField(
            model_name='tagalias',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d\\:-_]+$'), message='Enter a valid tag name.')]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d_\\- ]+\\Z'), message='Enter a valid collection name.')]),
        ),
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'tag categories'},
        ),
        migrations.RemoveIndex(
            model_name='tagcategory',
            name='tag_category_name_idx',
        ),
        migrations.AddIndex(
            model_name='tagcategory',
            index=models.Index(fields=['name', 'parent'], name='tag_category_name_parent_idx'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveIndex(
            model_name='tagcategory',
            name='tag_category_name_parent_idx',
        ),
        migrations.AddIndex(
            model_name='tagcategory',
            index=models.Index(fields=['name'], name='tag_category_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='tagcategory',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name_parent', nulls_distinct=False),
        ),
        migrations.AlterModelOptions(
            name='posttaghistory',
            options={'verbose_name_plural': 'Post tag histories'},
        ),
        migrations.AlterModelOptions(
            name='sourcehistory',
            options={'verbose_name_plural': 'Source histories'},
        ),
    ]
