# Generated by Django 5.2.7 on 2025-11-07 20:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tesys_tagboard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orig_name", models.TextField()),
                (
                    "upload_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edit_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "media",
            },
        ),
        migrations.CreateModel(
            name="MediaSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TagCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BA", "basic"),
                            ("AT", "artist"),
                            ("CP", "copyright"),
                            ("RT", "rating"),
                        ],
                        max_length=2,
                    ),
                ),
                ("prefix", models.CharField(max_length=24, unique=True)),
            ],
            options={
                "verbose_name_plural": "tag categories",
            },
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tesys_tagboard.media",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        unique=True, upload_to=tesys_tagboard.models.unique_filename
                    ),
                ),
            ],
            bases=("tesys_tagboard.media",),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tesys_tagboard.media",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        unique=True, upload_to=tesys_tagboard.models.unique_filename
                    ),
                ),
                (
                    "phash",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-z]{16}$")
                        ]
                    ),
                ),
                (
                    "dhash",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-z]{16}$")
                        ]
                    ),
                ),
            ],
            bases=("tesys_tagboard.media",),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tesys_tagboard.media",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        unique=True, upload_to=tesys_tagboard.models.unique_filename
                    ),
                ),
            ],
            bases=("tesys_tagboard.media",),
        ),
        migrations.AddField(
            model_name="media",
            name="source",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tesys_tagboard.mediasource",
            ),
        ),
        migrations.CreateModel(
            name="MediaType",
            fields=[
                ("name", models.TextField(unique=True)),
                ("template", models.TextField(primary_key=True, serialize=False)),
                ("desc", models.TextField(default="")),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("template__startswith", "image/"),
                            ("template__startswith", "audio/"),
                            ("template__startswith", "video/"),
                            _connector="OR",
                        ),
                        name="media_valid_mime_category",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="media",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tesys_tagboard.mediatype",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rating_level", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tesys_tagboard.tagcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "tag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="tesys_tagboard.tag",
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "post_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "media",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="tesys_tagboard.media",
                    ),
                ),
                ("tags", models.ManyToManyField(to="tesys_tagboard.tag")),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["post_date"],
            },
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("desc", models.TextField(max_length=1024)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("posts", models.ManyToManyField(to="tesys_tagboard.post")),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tesys_tagboard.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tesys_tagboard.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tesys_tagboard.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "tag"), name="unique_tagalias_name_tag"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_tag_name_cat"
            ),
        ),
        migrations.AddConstraint(
            model_name="pool",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_pool_name_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_favorite"
            ),
        ),
    ]
