# Generated by Django 5.2.7 on 2025-11-05 19:37

from django.db import migrations
from django.db.models import Model

class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0001_initial'),
    ]

    operations = []
