# Generated by Django 6.0 on 2026-01-04 22:06

from django.db import migrations
from django.db.models import Model

def define_moderator_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    mod = Group(id=1, name="Moderators")

    perms = Permission.objects.filter(codename__in=[
        # Default Django model perms
        "add_artist",
        "add_audio",
        "add_collection",
        "add_comment",
        "add_image",
        "add_post",
        "add_tag",
        "add_tagalias",
        "add_video",
        "change_artist",
        "change_audio",
        "change_collection",
        "change_image",
        "change_post",
        "change_tag",
        "change_tagalias",
        "change_video",
        "delete_artist",
        "delete_audio",
        "delete_collection",
        "delete_image",
        "delete_post",
        "delete_tag",
        "delete_tagalias",
        "delete_video",
        "view_artist",
        "view_audio",
        "view_collection",
        "view_comment",
        "view_group",
        "view_image",
        "view_post",
        "view_tag",
        "view_tagalias",
        "view_video",
        # Custom perms
        "lock_comments",
    ])

    mod.permissions.set(perms)

    mod.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(define_moderator_group),
    ]
