# Generated by Django 6.0 on 2026-01-18 20:00

import tesys_tagboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0002_add_moderator_auth_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(height_field='thumbnail_height', null=True, upload_to=tesys_tagboard.models.media_thumbnail_upload_path, width_field='thumbnail_width'),
        ),
    ]
