# Generated by Django 6.0.3 on 2026-03-23 02:18

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'artist', 'verbose_name_plural': 'artists'},
        ),
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': 'audio', 'verbose_name_plural': 'audios'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': [('add_post_to_collection', 'Can add posts to a collection'), ('remove_post_from_collection', 'Can remove posts from a collection')], 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post_date'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='defaultposttag',
            options={'verbose_name': 'default post tag', 'verbose_name_plural': 'default post tags'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'favorite', 'verbose_name_plural': 'favorites'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_date'], 'permissions': [('lock_comments', 'Can lock and unlock the comments of a post')], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='posttaghistory',
            options={'verbose_name': 'post tag history', 'verbose_name_plural': 'post tag histories'},
        ),
        migrations.AlterModelOptions(
            name='sourcehistory',
            options={'verbose_name': 'source history', 'verbose_name_plural': 'source histories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', '-post_count'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='tagalias',
            options={'ordering': ['name'], 'verbose_name': 'tag alias', 'verbose_name_plural': 'tag aliases'},
        ),
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'ordering': ['name'], 'verbose_name': 'tag category', 'verbose_name_plural': 'tag categories'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='bg',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Background color for tags in this category', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='fg',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Text color for tags in this category', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='A parent tag category. Used for organizing tag categories into groups', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesys_tagboard.tagcategory'),
        ),
    ]
