# Generated by Django 5.2.7 on 2025-11-07 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0002_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="md5",
            field=models.CharField(
                default="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                validators=[django.core.validators.RegexValidator("^[0-9A-Z]{32}$")],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="md5",
            field=models.CharField(
                default="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                validators=[django.core.validators.RegexValidator("^[0-9A-Z]{32}$")],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="md5",
            field=models.CharField(
                default="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                validators=[django.core.validators.RegexValidator("^[0-9A-Z]{32}$")],
            ),
            preserve_default=False,
        ),
    ]
