# Generated by Django 6.0.2 on 2026-03-18 23:12

import colorfield.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import re
import tesys_tagboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tesys_tagboard', '0003_alter_image_thumbnail'), ('tesys_tagboard', '0004_post_parent'), ('tesys_tagboard', '0005_remove_post_upload_date'), ('tesys_tagboard', '0006_alter_comment_options'), ('tesys_tagboard', '0007_alter_post_type_audio_audio_md5_idx_and_more'), ('tesys_tagboard', '0008_alter_collection_options'), ('tesys_tagboard', '0009_tagcategory_remove_tag_tag_category_idx_and_more'), ('tesys_tagboard', '0011_alter_tagcategory_name'), ('tesys_tagboard', '0012_alter_tagcategory_bg_alter_tagcategory_fg'), ('tesys_tagboard', '0013_alter_tagcategory_bg_alter_tagcategory_fg'), ('tesys_tagboard', '0014_defaultposttag'), ('tesys_tagboard', '0015_alter_tag_name_alter_tagalias_name'), ('tesys_tagboard', '0016_alter_tag_name_alter_tagalias_name'), ('tesys_tagboard', '0017_alter_collection_name'), ('tesys_tagboard', '0018_alter_tagcategory_options_and_more_updated'), ('tesys_tagboard', '0019_remove_tagcategory_unique_name_parent_and_more'), ('tesys_tagboard', '0020_alter_posttaghistory_options_and_more')]

    dependencies = [
        ('tesys_tagboard', '0002_add_moderator_auth_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(height_field='thumbnail_height', null=True, upload_to=tesys_tagboard.models.media_thumbnail_upload_path, width_field='thumbnail_width'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesys_tagboard.post'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_date',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AVIF', 'AVIF image'), ('BMP', 'Windows Bitmap Graphics'), ('GIF', 'GIF'), ('JPEG', 'JPEG image'), ('PNG', 'PNG'), ('WEBP', 'WEBP image'), ('TIFF', 'TIFF image'), ('MP3', 'MP3 audio'), ('WAV', 'WAV audio'), ('WAV2', 'WAV audio'), ('WAV3', 'WAV audio'), ('MP4', 'MP4 video'), ('MPEG', 'MPEG video'), ('WEBM', 'WEBM video')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='audio_md5_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='image_md5_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.HashIndex(models.F('phash'), name='image_phash_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.HashIndex(models.F('dhash'), name='image_dhash_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(models.F('category'), name='tag_category_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='video_md5_idx'),
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': [('add_post_to_collection', 'Can add posts to a collection'), ('remove_post_from_collection', 'Can remove posts from a collection')]},
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bg', models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$')])),
                ('fg', models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$')])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='tag_category_idx',
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesys_tagboard.tagcategory'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.tagcategory'),
        ),
        migrations.AddIndex(
            model_name='tagcategory',
            index=models.Index(models.F('name'), name='tag_category_name_idx'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='bg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='fg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.CreateModel(
            name='DefaultPostTag',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tesys_tagboard.tag')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d\\:-_]+$'), message='Enter a valid tag name.')]),
        ),
        migrations.AlterField(
            model_name='tagalias',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d\\:-_]+$'), message='Enter a valid tag name.')]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d_\\- ]+\\Z'), message='Enter a valid collection name.')]),
        ),
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'tag categories'},
        ),
        migrations.RemoveIndex(
            model_name='tagcategory',
            name='tag_category_name_idx',
        ),
        migrations.AddIndex(
            model_name='tagcategory',
            index=models.Index(fields=['name', 'parent'], name='tag_category_name_parent_idx'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveIndex(
            model_name='tagcategory',
            name='tag_category_name_parent_idx',
        ),
        migrations.AddIndex(
            model_name='tagcategory',
            index=models.Index(fields=['name'], name='tag_category_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='tagcategory',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name_parent', nulls_distinct=False),
        ),
        migrations.AlterModelOptions(
            name='posttaghistory',
            options={'verbose_name_plural': 'Post tag histories'},
        ),
        migrations.AlterModelOptions(
            name='sourcehistory',
            options={'verbose_name_plural': 'Source histories'},
        ),
    ]
