# Generated by Django 6.0.3 on 2026-03-24 17:05

import tesys_tagboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0003_alter_artist_options_alter_audio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='mimetype',
            field=models.CharField(default='image/png', max_length=30, validators=[tesys_tagboard.validators.mimetype_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='mimetype',
            field=models.CharField(default='image/png', max_length=30, validators=[tesys_tagboard.validators.mimetype_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='mimetype',
            field=models.CharField(default='image/png', max_length=30, validators=[tesys_tagboard.validators.mimetype_validator]),
            preserve_default=False,
        ),
    ]
