# Generated by Django 5.2.7 on 2025-11-06 20:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tesys_tagboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0003_add_constraints_and_pkeys"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orig_name", models.TextField()),
                (
                    "upload_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edit_date", models.DateTimeField(auto_now=True)),
                ("source", models.URLField(default="", max_length=255)),
                (
                    "md5",
                    models.CharField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9A-Z]{32}$")
                        ],
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tesys_tagboard.mediatype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "media metadata",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.CreateModel(
            name="MediaAudio",
            fields=[
                (
                    "mediametadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tesys_tagboard.mediametadata",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        unique=True, upload_to=tesys_tagboard.models.unique_filename
                    ),
                ),
            ],
            bases=("tesys_tagboard.mediametadata",),
        ),
        migrations.CreateModel(
            name="MediaImage",
            fields=[
                (
                    "mediametadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tesys_tagboard.mediametadata",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        unique=True, upload_to=tesys_tagboard.models.unique_filename
                    ),
                ),
                (
                    "phash",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-z]{16}$")
                        ]
                    ),
                ),
                (
                    "dhash",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-z]{16}$")
                        ]
                    ),
                ),
            ],
            bases=("tesys_tagboard.mediametadata",),
        ),
        migrations.CreateModel(
            name="MediaVideo",
            fields=[
                (
                    "mediametadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tesys_tagboard.mediametadata",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        unique=True, upload_to=tesys_tagboard.models.unique_filename
                    ),
                ),
            ],
            bases=("tesys_tagboard.mediametadata",),
        ),
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="tesys_tagboard.mediametadata",
            ),
        ),
        migrations.DeleteModel(
            name="Media",
        ),
        migrations.CreateModel(
            name="MediaSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="mediametadata",
            name="source",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tesys_tagboard.mediasource",
            ),
        ),
    ]
