# Generated by Django 6.0 on 2026-01-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0004_post_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload_date',
        ),
    ]
