# Generated by Django 6.0.3 on 2026-03-28 21:37

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0004_audio_mimetype_image_mimetype_video_mimetype'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AVIF', 'AVIF image'), ('BMP', 'Windows Bitmap Graphics'), ('GIF', 'GIF'), ('JPEG', 'JPEG image'), ('PNG', 'PNG'), ('WEBP', 'WEBP image'), ('TIFF', 'TIFF image'), ('MP3', 'MP3 audio'), ('WAV', 'WAV audio'), ('WAV2', 'WAV audio'), ('WAV3', 'WAV audio'), ('WAV4', 'WAV audio'), ('MP4', 'MP4 video'), ('MPEG', 'MPEG video'), ('WEBM', 'WEBM video')], max_length=20),
        ),
    ]
