# Generated by Django 6.0.3 on 2026-03-28 21:39

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0005_alter_post_managers_alter_post_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('tags', django.db.models.manager.Manager()),
            ],
        ),
    ]
