# Generated by Django 6.0 on 2026-01-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0005_remove_post_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post_date']},
        ),
    ]
