# Generated by Django 6.0.3 on 2026-03-28 21:57

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0006_alter_tag_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='favorite',
            managers=[
                ('favorites', django.db.models.manager.Manager()),
            ],
        ),
    ]
