# Generated by Django 6.0 on 2026-01-26 17:03

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AVIF', 'AVIF image'), ('BMP', 'Windows Bitmap Graphics'), ('GIF', 'GIF'), ('JPEG', 'JPEG image'), ('PNG', 'PNG'), ('WEBP', 'WEBP image'), ('TIFF', 'TIFF image'), ('MP3', 'MP3 audio'), ('WAV', 'WAV audio'), ('WAV2', 'WAV audio'), ('WAV3', 'WAV audio'), ('MP4', 'MP4 video'), ('MPEG', 'MPEG video'), ('WEBM', 'WEBM video')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='audio_md5_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='image_md5_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.HashIndex(models.F('phash'), name='image_phash_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.HashIndex(models.F('dhash'), name='image_dhash_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(models.F('category'), name='tag_category_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.HashIndex(models.F('md5'), name='video_md5_idx'),
        ),
    ]
