# Generated by Django 6.0.3 on 2026-03-28 22:33

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0007_alter_favorite_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tagalias',
            managers=[
                ('aliases', django.db.models.manager.Manager()),
            ],
        ),
    ]
