# Generated by Django 6.0.1 on 2026-01-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0007_alter_post_type_audio_audio_md5_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': [('add_post_to_collection', 'Can add posts to a collection'), ('remove_post_from_collection', 'Can remove posts from a collection')]},
        ),
    ]
