# Generated by Django 5.2.7 on 2025-11-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tesys_tagboard",
            "0004_mediametadata_alter_post_post_date_mediaaudio_and_more_squashed_0007_alter_mediametadata_source",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MediaAudio",
            new_name="Audio",
        ),
        migrations.RenameModel(
            old_name="MediaImage",
            new_name="Image",
        ),
        migrations.RenameModel(
            old_name="MediaVideo",
            new_name="Video",
        ),
    ]
