# Generated by Django 6.0.1 on 2026-02-05 00:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0008_alter_collection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bg', models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$')])),
                ('fg', models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$')])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='tag_category_idx',
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesys_tagboard.tagcategory'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.tagcategory'),
        ),
        migrations.AddIndex(
            model_name='tagcategory',
            index=models.Index(models.F('name'), name='tag_category_name_idx'),
        ),
    ]
