# Generated by Django 6.0.3 on 2026-04-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0008_alter_tagalias_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Safe'), (1, 'Unrated'), (50, 'Questionable'), (100, 'Explicit')], default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.tagcategory'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='rating_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Safe'), (1, 'Unrated'), (50, 'Questionable'), (100, 'Explicit')], default=0),
        ),
    ]
