# Generated by Django 5.2.7 on 2025-11-12 19:41

from django.db import migrations
from django.db.models import Model
from tesys_tagboard.enums import TagCategory

class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0009_alter_tag_category_delete_tagcategory"),
    ]

    operations = []

