# Generated by Django 6.0.3 on 2026-04-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0009_alter_post_rating_level_alter_tag_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag_name_cat',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_tag_name_cat', nulls_distinct=False),
        ),
    ]
