# Generated by Django 6.0.1 on 2026-02-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0010_add_default_tag_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
