# Generated by Django 6.0.3 on 2026-04-13 19:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0010_remove_tag_unique_tag_name_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='dark_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Background color for tags in this category in dark mode', image_field=None, max_length=25, null=True, samples=None, verbose_name='dark mode text'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='dark_fg',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Text color for tags in this category in dark mode', image_field=None, max_length=25, null=True, samples=None, verbose_name='dark mode text'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='light_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Background color for tags in this category in light mode', image_field=None, max_length=25, null=True, samples=None, verbose_name='light mode background'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='light_fg',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Text color for tags in this category in light mode', image_field=None, max_length=25, null=True, samples=None, verbose_name='light mode text'),
        ),
    ]
