# Generated by Django 6.0.1 on 2026-02-05 22:20

import colorfield.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0011_alter_tagcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='bg',
            field=colorfield.fields.ColorField(default='', image_field=None, max_length=25, samples=None, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='fg',
            field=colorfield.fields.ColorField(default='', image_field=None, max_length=25, samples=None, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$')]),
        ),
    ]
