# Generated by Django 6.0.3 on 2026-04-15 13:25

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0011_alter_tagcategory_dark_bg_alter_tagcategory_dark_fg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='desc',
            field=models.TextField(max_length=1024, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d_\\- ]+\\Z'), message='Enter a valid collection name.'), django.core.validators.MaxLengthValidator(128)]),
        ),
    ]
