# Generated by Django 5.2.7 on 2025-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0011_post_rating_level_alter_tag_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="type",
            field=models.CharField(
                choices=[
                    ("AVIF", "AVIF image"),
                    ("BMP", "Windows Bitmap Graphics"),
                    ("GIF", "GIF"),
                    ("JPEG", "JPEG image"),
                    ("PNG", "PNG"),
                    ("WEBP", "WEBP image"),
                    ("MP3", "MP3 audio"),
                    ("WAV", "WAV audio"),
                    ("MP4", "MP4 video"),
                    ("MPEG", "MPEG video"),
                    ("WEBM", "WEBM video"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="MediaType",
        ),
    ]
