# Generated by Django 5.2.7 on 2025-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0012_alter_media_type_delete_mediatype"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="artist",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="media",
            name="src_url",
            field=models.URLField(blank=True, default="", max_length=255),
        ),
    ]
