# Generated by Django 6.0.1 on 2026-02-06 05:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0012_alter_tagcategory_bg_alter_tagcategory_fg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='bg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='fg',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
