# Generated by Django 5.2.7 on 2025-11-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0013_tag_description_alter_artist_bio_alter_media_src_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagalias",
            options={"ordering": ["name"], "verbose_name_plural": "tag aliases"},
        ),
    ]
