# Generated by Django 6.0.2 on 2026-02-06 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0013_alter_tagcategory_bg_alter_tagcategory_fg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPostTag',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tesys_tagboard.tag')),
            ],
        ),
    ]
