# Generated by Django 6.0.2 on 2026-02-10 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0014_defaultposttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\d\\:-_]+$')]),
        ),
        migrations.AlterField(
            model_name='tagalias',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\d\\:-_]+$')]),
        ),
    ]
