# Generated by Django 6.0.2 on 2026-02-17 13:47

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0015_alter_tag_name_alter_tagalias_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d\\:-_]+$'), message='Enter a valid tag name.')]),
        ),
        migrations.AlterField(
            model_name='tagalias',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d\\:-_]+$'), message='Enter a valid tag name.')]),
        ),
    ]
