# Generated by Django 5.2.7 on 2025-11-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0015_alter_audio_file_alter_image_file_alter_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="post_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
