# Generated by Django 6.0.2 on 2026-02-25 19:40

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0016_alter_tag_name_alter_tagalias_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z\\d_\\- ]+\\Z'), message='Enter a valid collection name.')]),
        ),
    ]
