# Generated by Django 6.0.2 on 2026-02-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0017_alter_collection_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'tag categories'},
        ),
        migrations.RemoveIndex(
            model_name='tagcategory',
            name='tag_category_name_idx',
        ),
        migrations.AddIndex(
            model_name='tagcategory',
            index=models.Index(fields=['name', 'parent'], name='tag_category_name_parent_idx'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveIndex(
            model_name='tagcategory',
            name='tag_category_name_parent_idx',
        ),
        migrations.AddIndex(
            model_name='tagcategory',
            index=models.Index(fields=['name'], name='tag_category_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='tagcategory',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name_parent'),
        ),
    ]
