# Generated by Django 6.0.2 on 2026-03-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0018_alter_tagcategory_options_and_more_updated'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tagcategory',
            name='unique_name_parent',
        ),
        migrations.AddConstraint(
            model_name='tagcategory',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name_parent', nulls_distinct=False),
        ),
    ]
