# Generated by Django 5.2.7 on 2025-11-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0018_collection_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
