# Generated by Django 6.0.2 on 2026-03-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0019_remove_tagcategory_unique_name_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttaghistory',
            options={'verbose_name_plural': 'Post tag histories'},
        ),
        migrations.AlterModelOptions(
            name='sourcehistory',
            options={'verbose_name_plural': 'Source histories'},
        ),
    ]
