# Generated by Django 5.2.7 on 2025-12-04 20:41

import tesys_tagboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0020_comment_edit_date_comment_post_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="image",
            name="thumbnail_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="image",
            name="thumbnail_width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="image",
            name="width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                height_field="height",
                unique=True,
                upload_to=tesys_tagboard.models.media_upload_path,
                width_field="width",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(
                height_field="height",
                null=True,
                unique=True,
                upload_to=tesys_tagboard.models.media_thumbnail_upload_path,
                width_field="width",
            ),
        ),
    ]
