# Generated by Django 6.0 on 2025-12-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0024_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="public",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
