# Generated by Django 6.0 on 2026-01-05 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0028_add_moderator_auth_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTagHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_time', models.DateTimeField(auto_now_add=True, db_comment="Timestamp of Post's tags modification (including initial)")),
                ('tags', models.CharField(db_comment='Comma-delimited string of tag IDs at the current time', default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
