# Generated by Django 6.0 on 2026-01-06 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0029_posttaghistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSourceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_time', models.DateTimeField(auto_now_add=True, db_comment="Timestamp of Media's source URL modification (including initial)")),
                ('src_url', models.CharField(db_comment='Comma-delimited string of source URLs at the current time', default='')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesys_tagboard.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
