# Generated by Django 6.0 on 2026-01-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0030_mediasourcehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tesys_tagboard.tag'),
        ),
    ]
