# Generated by Django 6.0 on 2026-01-14 21:10

import tesys_tagboard.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blur_rating_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SAFE'), (1, 'UNRATED'), (50, 'QUESTIONABLE'), (100, 'EXPLICIT')], db_comment="An integer matching one of the options for a Post's rating_level", default=tesys_tagboard.enums.RatingLevel['EXPLICIT']),
        ),
        migrations.AddField(
            model_name='user',
            name='blur_tags',
            field=models.ManyToManyField(blank=True, related_name='blur_tags_users', to='tesys_tagboard.tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='filter_tags',
            field=models.ManyToManyField(blank=True, related_name='filter_tags_users', to='tesys_tagboard.tag'),
        ),
    ]
