# Generated by Django 6.0 on 2026-01-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0030_mediasourcehistory'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blur_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Safe'), (1, 'Unrated'), (50, 'Questionable'), (100, 'Explicit')], db_comment="An integer matching one of the options for a Post's rating_level", default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='blur_tags',
            field=models.ManyToManyField(related_name='blur_tags_users', to='tesys_tagboard.tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='filter_tags',
            field=models.ManyToManyField(related_name='filter_tags_users', to='tesys_tagboard.tag'),
        ),
    ]
