# Generated by Django 6.0 on 2026-01-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_blur_level_user_blur_tags_user_filter_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blur_level',
            new_name='blur_rating_level',
        ),
    ]
