# Generated by Django 6.0.3 on 2026-04-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_blur_rating_level_user_blur_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blur_rating_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Safe'), (1, 'Unrated'), (50, 'Questionable'), (100, 'Explicit')], db_comment="An integer matching one of the options for a Post's rating_level", default=100),
        ),
    ]
