# Generated by Django 6.0 on 2026-01-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0031_alter_post_tags'),
        ('users', '0003_rename_blur_level_user_blur_rating_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blur_tags',
            field=models.ManyToManyField(blank=True, related_name='blur_tags_users', to='tesys_tagboard.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='filter_tags',
            field=models.ManyToManyField(blank=True, related_name='filter_tags_users', to='tesys_tagboard.tag'),
        ),
    ]
